FROM nginx:latest
COPY ./public /usr/share/nginx/html
COPY ./PII /user/share/nginx/html
ENV ACCESS_KEY=AKIAABPX3123CJ5POOJD
ENV ACCESS_SECRET=s1bP72zEwsd9wZAx508HaAS4Fl/mHm6WwetrO/34
ENV Credit_Card=4222222222222
ENV email=trivy@aquasec.com
ENV jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
